name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Test Sonar Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Test internet access
        run: curl -f https://www.google.com/
      - name: Ping SonarQube server
        run: curl -I http://192.168.1.29:9000/
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      # - name: Download Sonar Scanner
      #   run: |
      #    curl -SL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/macosx/latest/sonar-scanner-cli-macosx-latest.zip -o sonar-scanner.zip
      #    unzip sonar-scanner.zip
      # - name: Run Sonar Scanner
      #   run: ./sonar-scanner-cli/bin/sonar-scanner -Dsonar.projectKey=GitHub-repo
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
